all:
  children:
    production:
      hosts:
        production-server:
          ansible_host: "${SERVER_IP}"
          ansible_user: "${SERVER_USER}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      vars:
        ansible_python_interpreter: /usr/bin/python3