all:
  children:
    servers:
      hosts:
        production:
          ansible_host: "{{ lookup('env', 'SERVER_IP') }}"
          ansible_user: "{{ lookup('env', 'SERVER_USER', default='ubuntu') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH', default='~/.ssh/super-app-backend') }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          github_repository: "{{ lookup('env', 'GITHUB_REPOSITORY') }}"
      vars:
        ansible_python_interpreter: /usr/bin/python3
        # SSH configuration - use user's SSH directory for security
        ssh_directory: "{{ lookup('env', 'SSH_DIR', default='~/.ssh') }}"
        ssh_private_key: "{{ lookup('env', 'SSH_KEY_PATH', default='~/.ssh/super-app-backend') }}"
        ssh_public_key: "{{ lookup('env', 'SSH_KEY_PATH', default='~/.ssh/super-app-backend') }}.pub" 