name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        
    - name: Create secrets directory
      run: mkdir -p secrets
      
    - name: Create secrets files
      run: |
        echo "${{ secrets.DB_PASSWORD }}" > secrets/db_password
        echo "${{ secrets.API_KEY }}" > secrets/api_key
        
    - name: Deploy with Ansible (using superapp user)
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
      run: |
        # Use superapp user instead of root
        ansible-playbook -i ansible/inventory.yml ansible/deploy.yml \
          --user superapp \
          --private-key ~/.ssh/super-app-backend \
          --extra-vars "ansible_become=yes ansible_become_user=root ansible_become_method=sudo" 