name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      IP_SALT: ${{ secrets.IP_SALT }}
      USER_AGENT_SALT: ${{ secrets.USER_AGENT_SALT }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with coverage
        run: |
          pytest --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/unit/ -v --disable-warnings --tb=short

      - name: Run CORS tests
        run: |
          pytest --cov-append --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/test_cors.py -v --disable-warnings --tb=short

      - name: Run integration tests with coverage
        run: |
          pytest --cov-append --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/integration/ -v --disable-warnings --tb=short

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      IP_SALT: ${{ secrets.IP_SALT }}
      USER_AGENT_SALT: ${{ secrets.USER_AGENT_SALT }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./"
          target: ${{ secrets.BACKEND_DIR }}

      - name: Deploy and restart container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.BACKEND_DIR }}
            docker compose build
            docker compose up -d --force-recreate
            docker compose exec api python db/migrate_incremental.py migrate
            sleep 3
            for i in {1..5}; do
              if curl --fail http://localhost/ping; then
                echo "Health check passed."
                break
              else
                echo "Health check failed. Retrying in 1s... ($i/5)"
                sleep 1
              fi
            done
