name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/super-app-backend
        chmod 600 ~/.ssh/super-app-backend
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        
    - name: Create secrets directory
      run: mkdir -p secrets
      
    - name: Create secrets files
      run: |
        echo "${{ secrets.DB_PASSWORD }}" > secrets/db_password
        echo "${{ secrets.API_KEY }}" > secrets/api_key
        
    - name: Debug SSH setup
      run: |
        echo "SSH key exists: $(ls -la ~/.ssh/super-app-backend)"
        echo "SSH key permissions: $(stat -c '%a' ~/.ssh/super-app-backend)"
        echo "SSH key first line: $(head -1 ~/.ssh/super-app-backend)"
        echo "SSH key last line: $(tail -1 ~/.ssh/super-app-backend)"
        echo "Known hosts: $(cat ~/.ssh/known_hosts)"
        
    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/super-app-backend -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH connection successful'"
        
    - name: Deploy with Ansible
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        SERVER_IP: ${{ secrets.SERVER_IP }}
        ANSIBLE_USER: ${{ secrets.SERVER_USER }}
        SSH_KEY_FILE: ~/.ssh/super-app-backend
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        echo "Environment variables:"
        echo "SERVER_IP: $SERVER_IP"
        echo "ANSIBLE_USER: $ANSIBLE_USER"
        echo "SSH_KEY_FILE: $SSH_KEY_FILE"
        ansible-playbook -i ansible/inventory.yml ansible/deploy.yml 