name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      IP_SALT: ${{ secrets.IP_SALT }}
      USER_AGENT_SALT: ${{ secrets.USER_AGENT_SALT }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with SQLite (fast feedback)
        run: |
          pytest --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/unit/ -v --disable-warnings --tb=short

      - name: Run CORS tests with SQLite
        run: |
          pytest --cov-append --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/test_cors.py -v --disable-warnings --tb=short

      - name: Run migration unit tests with SQLite
        run: |
          pytest --cov-append --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/unit/test_migrations.py -v --disable-warnings --tb=short

# Temporarily disabled test-postgresql job
#  test-postgresql:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:16
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: test_db
#          POSTGRES_USER: postgres
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
#    env:
#      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
#      IP_SALT: ${{ secrets.IP_SALT }}
#      USER_AGENT_SALT: ${{ secrets.USER_AGENT_SALT }}
#      CLIENT_URL: ${{ secrets.CLIENT_URL }}
#      # PostgreSQL test configuration
#      DB_HOST: localhost
#      DB_PORT: 5432
#      DB_NAME: test_db
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      ENVIRONMENT: test
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Cache pip
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Wait for PostgreSQL to be ready
#        run: |
#          echo "Waiting for PostgreSQL to be ready..."
#          until pg_isready -h localhost -p 5432 -U postgres; do
#            echo "PostgreSQL is not ready yet. Waiting..."
#            sleep 2
#          done
#          echo "PostgreSQL is ready!"
#
#      - name: Run integration tests with PostgreSQL
#        run: |
#          pytest --cov=apps --cov=db --cov=core --cov-report=xml --cov-report=term-missing tests/integration/ -v --disable-warnings --tb=short

  deploy:
    runs-on: ubuntu-latest
    needs: [test-sqlite]
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      IP_SALT: ${{ secrets.IP_SALT }}
      USER_AGENT_SALT: ${{ secrets.USER_AGENT_SALT }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./"
          target: ${{ secrets.BACKEND_DIR }}

      - name: Deploy and restart container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.BACKEND_DIR }}
            docker compose build
            docker compose up -d --force-recreate
            
            # Wait for container to be healthy before running migrations
            echo "Waiting for container to be healthy..."
            for i in {1..30}; do
              if docker compose ps api | grep -q "healthy"; then
                echo "Container is healthy. Proceeding with migrations..."
                break
              elif [ $i -eq 30 ]; then
                echo "Container failed to become healthy within 30 attempts"
                docker compose logs api
                exit 1
              else
                echo "Container not healthy yet. Waiting... ($i/30)"
                sleep 2
              fi
            done
            
            # Run migrations with retry mechanism
            echo "Running database migrations..."
            for i in {1..3}; do
              if docker compose exec -T api python db/migrate_incremental.py migrate; then
                echo "Migrations completed successfully"
                break
              else
                echo "Migration attempt $i failed. Retrying in 3s..."
                if [ $i -eq 3 ]; then
                  echo "All migration attempts failed"
                  docker compose logs api
                  exit 1
                fi
                sleep 3
              fi
            done
            
            # Final health check
            sleep 3
            for i in {1..5}; do
              if curl --fail http://localhost/ping; then
                echo "Health check passed."
                break
              else
                echo "Health check failed. Retrying in 1s... ($i/5)"
                sleep 1
              fi
            done
