name: Test, Migrate, and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio aiosqlite
        
    - name: Create .env file for tests
      run: |
        cp env.example .env
        echo "ENVIRONMENT=test" >> .env
        echo "DATABASE_URL=sqlite:///./test.db" >> .env
        
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --disable-warnings --tb=short
        
    - name: Run CORS tests
      run: |
        pytest tests/test_cors.py -v --disable-warnings --tb=short
        
    - name: Run integration tests (if database available)
      run: |
        pytest tests/integration/ -v --disable-warnings --tb=short || echo "Integration tests skipped - database not available"
      continue-on-error: true
        
    - name: Test database migrations
      run: |
        python db/migrate.py
        # Clean up test database file
        rm -f test.db
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  migrate:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    needs: test
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run database migrations
      run: |
        python db/migrate.py
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        
    - name: Verify database connection
      run: |
        python -c "
import asyncio
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath('.')))
from db.session import database
from core.config import settings

async def test_connection():
    try:
        await database.connect()
        result = await database.fetch_all('SELECT version();')
        print(f'✅ Database connection successful: {result[0][0]}')
        await database.disconnect()
    except Exception as e:
        print(f'❌ Database connection failed: {e}')
        sys.exit(1)

asyncio.run(test_connection())
        "
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, migrate]
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/super-app-backend
        chmod 600 ~/.ssh/super-app-backend
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        
    - name: Create secrets directory
      run: mkdir -p secrets
      
    - name: Create secrets files
      run: |
        echo "${{ secrets.DB_PASSWORD }}" > secrets/db_password
        echo "${{ secrets.API_KEY }}" > secrets/api_key
        
    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/super-app-backend -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH connection successful'"
        
    - name: Deploy with Ansible
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        SERVER_IP: ${{ secrets.SERVER_IP }}
        ANSIBLE_USER: ${{ secrets.SERVER_USER }}
        SSH_KEY_FILE: ~/.ssh/super-app-backend
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        echo "🚀 Starting deployment..."
        echo "Environment variables:"
        echo "SERVER_IP: $SERVER_IP"
        echo "ANSIBLE_USER: $ANSIBLE_USER"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "DB_HOST: $DB_HOST"
        echo "DB_PORT: $DB_PORT"
        echo "DB_NAME: $DB_NAME"
        echo "DB_USER: $DB_USER"
        ansible-playbook -i ansible/inventory.yml ansible/deploy.yml -v
        
    - name: Verify deployment
      run: |
        echo "🔍 Verifying deployment..."
        sleep 30  # Wait for container to start
        curl -f http://${{ secrets.SERVER_IP }}:8000/ping || echo "⚠️  Health check failed, but deployment may still be successful" 